input_jacobians_shape : [128, 32, 21]
input_torques_shape : [1, 7]

output_directory: output/
model_name: unet_dice_and_bce
optimizer: adam
scenario: 1
with_coordconv: True
with_wandb: True
n_filters: 16 
dropout: 0.5
batchnorm: True
metrics: 
  # - accuracy
  - dice
loss: 
  # - binary_crossentropy
  # - dice_and_iou
  - dice_and_bce
verbose: True



